export { EmailService } from './email.service.js'
export { getAppointmentsNeedingReminder, type AppointmentForReminder, type AppointmentsNeedingReminder } from './scheduler.js'
export * from './templates/appointment-confirmation.js'
export * from './templates/appointment-reminder.js'
export * from './templates/payment-reminder.js'
export * from './templates/review-request.js'
