export { EmailService } from './email.service.js'
export { getAppointmentsNeedingReminder, type AppointmentForReminder, type AppointmentsNeedingReminder } from './scheduler.js'
export * from './templates/appointment-confirmation.js'
export * from './templates/appointment-reminder.js'
export * from './templates/professional-new-booking.js'
export * from './templates/appointment-modified.js'
export * from './templates/appointment-cancelled-by-patient.js'
export * from './templates/professional-cancellation-notice.js'
export * from './templates/review-request.js'
export * from './templates/confirm-attendance-page.js'
export * from './templates/daily-digest.js'
export { generateGoogleCalendarUrl } from './utils/google-calendar.js'
export { generateICSFile, type ICSParams } from './utils/ics-generator.js'
